export const STRINGS = {
  AND: "and",
  RUPEES: "Rupees",
  PAISE: "Paise",
  COMMA: ",",
  SPACE: " ",
  ZERO: "Zero",
  ONE: "One",
  TWO: "Two",
  THREE: "Three",
  FOUR: "Four",
  FIVE: "Five",
  SIX: "Six",
  SEVEN: "Seven",
  EIGHT: "Eight",
  NINE: "Nine",
  TEN: "Ten",
  ELEVEN: "Eleven",
  TWELVE: "Twelve",
  THIRTEEN: "Thirteen",
  FOURTEEN: "Fourteen",
  FIFTEEN: "Fifteen",
  SIXTEEN: "Sixteen",
  SEVENTEEN: "Seventeen",
  EIGHTEEN: "Eighteen",
  NINETEEN: "Nineteen",
  TWENTY: "Twenty",
  THIRTY: "Thirty",
  FORTY: "Forty",
  FIFTY: "Fifty",
  SIXTY: "Sixty",
  SEVENTY: "Seventy",
  EIGHTY: "Eighty",
  NINETY: "Ninety",
  HUNDRED: "Hundred",
  THOUSAND: "Thousand",
  LAKH: "Lakh",
  CRORE: "Crore",
  LIMIT_EXCEED: "Max limit crossed!",
  MAX_LIMIT_EXCEED: "Maximum limit crossed!",
  MIN_LIMIT_EXCEED: "Minimum limit crossed!",
};
